config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'

  scope :admin, module: :admin, as: :admin do
    resources :users
    resources :rewards
    resources :points
  end

  resources :users, only: %i[new create show]
  resources :rewards, only: %i[index show create update destroy]
  resources :points, only: %i[index create destroy]

  resources :sessions, only: %i[index]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
# Defines Point Model behavior
class Point < ApplicationRecord
  validates :value, presence: true
  validates :description, presence: true
  belongs_to :user
end

app/models/reward.rb
# Defines the Reward Model
class Reward < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :cost, presence: true

  has_many :user_rewards
end

app/models/user.rb
# Defines user model
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :points
  has_many :user_rewards
  has_many :rewards, through: :user_rewards

  enum role: %w[default admin]

  def total_points
    points.sum(:value)
  end

  def self.alphabetize
    order(:name)
  end
end

app/models/user_reward.rb
class UserReward < ApplicationRecord
  validates :user_id, presence: true
  validates :reward_id, presence: true

  belongs_to :user
  belongs_to :reward
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  private

  def require_admin
    render file: '/public/404' unless current_admin?
  end
end

app/controllers/admin/points_controller.rb
# Defines Admin's rights for the PointsController
class Admin::PointsController < Admin::BaseController
  def index
    @users = User.all
  end

  def new
    @users = User.alphabetize
    @point = Point.new
  end

  def create
    point = Point.create(point_params)
    if point.save
      redirect_to admin_points_path
    else
      flash.notice = 'You must select a point value.'
      redirect_to new_admin_point_path
    end
  end

  def destroy
    Point.destroy(params[:id])
    redirect_to admin_points_path
  end

  private

  def point_params
    params.require(:point).permit(:value, :description, :user_id)
  end
end

app/controllers/admin/rewards_controller.rb
# Defines Admin rights for RewardsController
class Admin::RewardsController < Admin::BaseController
  def index
    @rewards = Reward.all
  end

  def new
    @reward = Reward.new
  end

  def edit
    @reward = Reward.find(params[:id])
  end
end

app/controllers/admin/users_controller.rb
# Defines Admin UsersController
class Admin::UsersController < Admin::BaseController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to admin_users_path
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    
  end
end

app/controllers/points_controller.rb
# Defines actions for Points Controller
class PointsController < ApplicationController
  def index
    @points = current_user.points
  end

  def create
    Point.create(point_params)
    UserReward.create(user_reward_params)
    flash.notice = 'You have acquired a reward!'
    redirect_to rewards_path
  end

  private

  def point_params
    params.require(:point).permit(:value, :description, :user_id)
  end

  def user_reward_params
    params.require(:user_reward).permit(:user_id, :reward_id)
  end
end

app/controllers/rewards_controller.rb
# Defines RewardsController Actions
class RewardsController < ApplicationController
  def index
    @rewards = Reward.all
  end

  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      redirect_to admin_rewards_path
    else
      redirect_to new_admin_reward_path
    end
  end

  def update
    @reward = Reward.find(params[:id])
    @reward.update(reward_params)
    redirect_to admin_rewards_path
  end

  def destroy
    Reward.destroy(params[:id])
    redirect_to admin_rewards_path
  end

  def show
    @reward = Reward.find(params[:id])
  end

  private

  def reward_params
    params.require(:reward).permit(:title, :description, :cost)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else

    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to sessions_path
  end
end

app/controllers/users_controller.rb
# Defines user controller actions
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.notice = 'Thanks for making an account! Log in now to see what all the fuss is about!'
      redirect_to login_path
    else
      flash.notice = 'Sorry--there was a problem! Please try again!'
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/points/index.html.erb
<h1>All Users and Their Points</h1>
<%= link_to 'Assign Points', new_admin_point_path %><br>
<% @users.each do |user| %>
  <%= link_to user.name, admin_user_path(user) %> - <%= user.email %> - Points: <%= user.total_points %><br>
<% end %>

app/views/admin/points/new.html.erb
<h3>Assign Points</h3>

<%= form_for [:admin, @point] do |f| %>
  <%= f.label :value %>
  <%= f.number_field :value %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :user %>
  <%= f.collection_select :user_id, @users, :id, :email %>
  <%= f.submit 'Assign Points' %>
<% end %>

app/views/admin/rewards/_form.html.erb
<%= form_for @reward do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :cost %>
  <%= f.number_field :cost %>
  <%= f.submit %>
<% end %>

app/views/admin/rewards/edit.html.erb
<h3>Edit <%= @reward.title %> </h3>

<%= render partial: 'form' %>

app/views/admin/rewards/index.html.erb
<h1>All Possible Rewards</h1><br>
<%= link_to 'Create New Reward', new_admin_reward_path %><br>
<% @rewards.each do |reward| %>
  <%= link_to reward.title, reward_path(reward) %> -
  <%= reward.description %> -
  Price: <%= reward.cost %> -
  <%= link_to 'Edit', edit_admin_reward_path(reward) %> -
  <%= link_to "Delete", reward_path(reward), method: 'delete', data: {confirm: "Are you sure? This will permanently delete this reward from all associated user accounts."} %>
  <br>
<% end %>

app/views/admin/rewards/new.html.erb
<h3>Create a New Reward</h3>
<%= render partial: 'form' %>

app/views/admin/users/index.html.erb
<h1>All Users</h1>

<%= link_to 'Create New User', new_admin_user_path %><br>
<% @users.each do |user| %>
  <%= user.name %> - <%= user.email %> <br>
<% end %>

app/views/admin/users/new.html.erb
<%= form_for [:admin, @user] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email, 'E-mail address' %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :role %>
  <%= f.select :role, ['default', 'admin'] %>
  <%= f.submit 'Create Account' %>
<% end %>

app/views/admin/users/show.html.erb
<h3> <%= @user.name %>'s total points: <%= @user.total_points  %> </h3>
<% @user.points.each do |point| %>
  <p>Points: <%= point.value %> - Description: <%= point.description %> - Created at: <%= point.created_at %> - Updated at: <%= point.updated_at %> - <%= link_to 'Delete', admin_point_path(point), method: 'delete', data: {confirm: "Are you sure? This will permanently delete this point from #{@user.name}'s account."} %></p>
<% end %>

app/views/dashboard/index.html.erb
<div class="middle-box">
  <div class="inner-middle-box">
    <h1>Welcome to the site! <%= link_to 'Create an account', new_user_path %> in order to see what's inside! </h1>  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PointBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
      <div class="topnav">
        <div class="inner-top-nav">
          <h1><%= link_to 'PointBox', user_path(current_user) %></h1>
        </div>
        <div class="inner-top-nav">
          <p><%= link_to 'See All Rewards', rewards_path %></p>
          <p><%= link_to 'Your Rewards', user_path(current_user) %></p>
          <p> <%= link_to 'Your Points History', points_path %></p>
        </div>
        <div class="right-top-nav">
            <p> Logged in as <%=link_to current_user.email, user_path(current_user) %></p>
            <p><%= link_to "Log out", logout_path, method: "delete" %></p>
          </div>

        </div>
    </div>
    <% else %>

    <div class="topnav">
      <div class="inner-top-nav">
        <h1><%= link_to 'PointBox', root_path %></h1>
      </div>
      <div class="inner-top-nav">
        <p><%= link_to 'Create New Account', new_user_path %></p>
      </div>
      <div class="right-top-nav">
          <p><%=link_to 'Log in', login_path %></p>
      </div>
    </div>
    <% end %>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/points/index.html.erb
<div class="middle-box">
  <div class="alt-inner-middle-box">
    <h1> <%= current_user.name %>'s Points History </h1>
    <h3>Point Balance: <%= current_user.total_points %> </h3>
    <h3> <%= link_to "<< Back to #{current_user.name}'s dashboard", user_path(current_user) %> </h3>
    <% @points.each do |point| %>
    <p> Points: <%= point.value %> - Description: <%= point.description %> - Created at: <%= point.created_at %>
      <% end %>

  </div>
</div>

app/views/rewards/index.html.erb
<div class="middle-box">
  <div class="table-inner-middle-box">
    <h1>All Possible Rewards</h1><br>
    <h3>Your points available to redeem: <%= current_user.total_points %></h3>
    <% @rewards.each do |reward| %>
    <table>
      <tr>
        <td><%= link_to reward.title, reward_path(reward) %></td>
        <td><%= reward.description %></td>
        <td>Price: <%= reward.cost %></td>
    <% end %>

  </div>

</div>

app/views/rewards/show.html.erb
<div class="middle-box">
  <div class="alt-inner-middle-box">
    <h3>Your points available to redeem: <%= current_user.total_points %></h3>
    <h1><%= @reward.title %></h1>
    <p><%= @reward.description %></p>
    <% if current_user.total_points >= @reward.cost %>
    <%= link_to "Redeem #{@reward.cost} of your #{current_user.total_points} points to acquire this reward.", points_path(point: { description: "Redeemed #{@reward.cost} points for #{@reward.title}", value: -@reward.cost, user_id: current_user.id }, user_reward: { user_id: current_user.id, reward_id: @reward.id } ), method: 'post' %>
    <% else %>
    <h3>You do not have enough points to acquire this reward.</h3>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="middle-box">
  <div class="inner-middle-box">
    <%= form_for @user do |f| %>
      <table>
        <tr>
          <td><%= f.label :name %></td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td><%= f.label :email, 'E-mail address' %></td>
          <td><%= f.email_field :email %></td>
        </tr>
        </tr>
          <td><%= f.label :password %></td>
          <td><%= f.password_field :password %></td>
        <tr>
          <td><%= f.submit 'Create Account' %></td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if current_user %>
<div class="middle-box">
  <div class="alt-inner-middle-box">
    <h1>Welcome back, <%= current_user.name %> </h1>
    <h3>Points available to redeem: <%= current_user.total_points %> </h3>

    <h4>Rewards you have acquired: </h4>

    <% if current_user.rewards.all.count == 0 %>
      <h3>You don't have any rewards. <%= link_to 'Acquire some rewards here.', rewards_path %></h3>
    <% else %>
      <% current_user.rewards.each do |reward| %>
        <p><%= link_to reward.title, reward_path(reward) %>
          for <%= reward.cost %> points.</p>
      <% end %>
    <% end %>
    <h3> <%= link_to 'See my points history', points_path %> </h3>
  </div>
</div>

<% else %>
  <h1>Welcome to the site! <%= link_to 'Create an account', new_user_path %> in order to see what's inside! </h1>
<% end %>